### ISSUE TITLE
QueueClient causes Azure SNAT exhaustion

### ISSUE THREAD

**Issue by danielcandea** [Nodinite/Nodinite.Serilog.ServiceBusSink#1]
A QueueClient should be [closed](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues) after usage, otherwise it could lead to Azure [SNAT exhaustion](https://docs.microsoft.com/en-us/azure/load-balancer/troubleshoot-outbound-connection#snatexhaust). We encountered this while using [Nodinite.Serilog.ServiceBusSink](https://github.com/Nodinite/Nodinite.Serilog.ServiceBusSink/blob/master/Nodinite.Serilog.ServiceBusSink/Nodinite.Serilog.ServiceBusSink/NodiniteServiceBusSink.cs) and raised a support ticket, #4398.

The fix would be to call `queueClient.CloseAsync().Wait();` after `queueClient.SendAsync(message).Wait();` in [ Nodinite.Serilog.ServiceBusSink](https://github.com/Nodinite/Nodinite.Serilog.ServiceBusSink/blob/master/Nodinite.Serilog.ServiceBusSink/Nodinite.Serilog.ServiceBusSink/NodiniteServiceBusSink.cs)

I tried creating a new branch and raise a PR with the fix but don't have rights.

**Comment by Anetre** [comment]
A new version is now released 1.0.6 that close the connection.
